---
title: "Job scraper"
output: html_document
---

```{r}
# Scraper

job_scraper <- function(position = "data analyst"){  # function expects two words
  
  library(tidyverse)
  library(rvest)
  library(xml2)
  library(digest)
  library(dplyr)
  
  # Set up dataframe
  full_df <- data.frame() # Primary data frame to store info
  
  # Format search term
  search <- paste0(str_split(position, " ")[[1]][1],
                     "%20",
                     str_split(position, " ")[[1]][2])
  
  #Format url
  url <- paste0("https://www.indeed.com/jobs?q=",search,"&l=Salt%20Lake%20City%2C%20UT&radius=50&fromage=1")
  
  # Read HTML
  page <- read_html(url) 
  
  # Get Job Title
  title <- page %>%
    html_nodes('.jobTitle') %>%
    html_nodes('span') %>%
    html_text('title')
  
  title <- title[!(title=='new')]
  
  # Get Company Name
  company <- page %>%
    html_nodes('.companyName') %>%
    html_text('companyName')
  
  # Get Location
  location <- page %>%
    html_nodes('.companyLocation') %>%
    html_text('companyLocation')
  
  # Get Link
  link <- page %>%
    html_nodes('[data-hide-spinner = "true"]') %>%
    html_attr('href')
  
  link <- sprintf("https://www.indeed.com%s", link) 
  
  # Get Job Descriptions
  job_description <- c() # Goes into each link and pulls full text
    for(j in seq_along(link)) {
      
      url_link <- link[j]
      page <- xml2::read_html(url_link)
      
      job_description[j] <- page %>%
          html_nodes('.jobsearch-jobDescriptionText') %>%
          html_text()
    }
  
  # Store in dataframe
  df <- data.frame(search = position, title, company, location, job_description, link)
  
  full_df <- bind_rows(full_df, df)
  
  # Clean description text and display table
   
  full_df$job_description <- gsub("[\r\n]", "*", full_df$job_description)
full_df

  # Create a unique id for each job posting attribute combination
  full_df$unique_id <- mapply(function(x, y, z) digest(paste0(x,y,z)), full_df$title, full_df$location, full_df$company)

  # Remove duplicate unique ids
  full_df <- full_df %>%
    distinct(unique_id, .keep_all = TRUE)

  # Remove duplicate links
  full_df <- full_df %>%
    distinct(link, .keep_all = TRUE)

list(results = full_df)

}
```

```{r}
job_scraper(position = "data analyst")$results
```

```{r}
job_scraper(position = "data scientist")$results
```

